"""create business schema

Revision ID: 20260719_0002
Revises: 20260719_0001
Create Date: 2026-07-19 10:45:57.823975
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "20260719_0002"
down_revision: str | None = "20260719_0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

PARTITIONED_TABLES = (
    "stock_daily",
    "stock_technical_daily",
    "stock_moneyflow_daily",
    "market_theme_member_daily",
    "etf_daily",
    "etf_share_size_daily",
)
INITIAL_PARTITIONS = (
    ("202607", "2026-07-01", "2026-08-01"),
    ("202608", "2026-08-01", "2026-09-01"),
    ("202609", "2026-09-01", "2026-10-01"),
    ("202610", "2026-10-01", "2026-11-01"),
)


def _create_initial_partitions() -> None:
    for table_name in PARTITIONED_TABLES:
        for suffix, start_date, end_date in INITIAL_PARTITIONS:
            op.execute(
                sa.text(
                    f"CREATE TABLE {table_name}_p{suffix} PARTITION OF {table_name} "
                    f"FOR VALUES FROM ('{start_date}') TO ('{end_date}')"
                )
            )


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "concept_board",
        sa.Column("source", sa.String(length=8), server_default="THS", nullable=False),
        sa.Column("ts_code", sa.String(length=20), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("member_count", sa.Integer(), nullable=True),
        sa.Column("exchange", sa.String(length=8), nullable=True),
        sa.Column("list_date", sa.Date(), nullable=True),
        sa.Column("board_type", sa.String(length=8), nullable=False),
        sa.Column("synced_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("source", "ts_code", name=op.f("pk_concept_board")),
    )
    op.create_table(
        "etf",
        sa.Column("ts_code", sa.String(length=16), nullable=False),
        sa.Column("csname", sa.String(length=64), nullable=True),
        sa.Column("extname", sa.String(length=96), nullable=True),
        sa.Column("cname", sa.String(length=192), nullable=True),
        sa.Column("index_code", sa.String(length=20), nullable=True),
        sa.Column("index_name", sa.String(length=192), nullable=True),
        sa.Column("setup_date", sa.Date(), nullable=True),
        sa.Column("list_date", sa.Date(), nullable=True),
        sa.Column("list_status", sa.String(length=1), nullable=False),
        sa.Column("exchange", sa.String(length=8), nullable=False),
        sa.Column("source_exchange", sa.String(length=8), nullable=False),
        sa.Column("mgr_name", sa.String(length=128), nullable=True),
        sa.Column("custod_name", sa.String(length=160), nullable=True),
        sa.Column("mgt_fee", sa.Numeric(precision=14, scale=8), nullable=True),
        sa.Column("etf_type", sa.String(length=32), nullable=True),
        sa.Column("synced_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("list_status IN ('L', 'D', 'P')", name=op.f("ck_etf_list_status")),
        sa.PrimaryKeyConstraint("ts_code", name=op.f("pk_etf")),
    )
    op.create_table(
        "market_index",
        sa.Column("ts_code", sa.String(length=20), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("fullname", sa.String(length=256), nullable=True),
        sa.Column("market", sa.String(length=16), nullable=False),
        sa.Column("publisher", sa.String(length=128), nullable=True),
        sa.Column("index_type", sa.String(length=64), nullable=True),
        sa.Column("category", sa.String(length=64), nullable=True),
        sa.Column("base_date", sa.Date(), nullable=True),
        sa.Column("base_point", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("list_date", sa.Date(), nullable=True),
        sa.Column("weight_rule", sa.String(length=128), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("exp_date", sa.Date(), nullable=True),
        sa.Column("synced_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("ts_code", name=op.f("pk_market_index")),
    )
    op.create_table(
        "market_theme_daily",
        sa.Column("source", sa.String(length=8), server_default="DC", nullable=False),
        sa.Column("theme_code", sa.String(length=20), nullable=False),
        sa.Column("trade_date", sa.Date(), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("pct_change", sa.Numeric(precision=14, scale=6), nullable=True),
        sa.Column("hot", sa.Numeric(precision=24, scale=6), nullable=True),
        sa.Column("rank", sa.Integer(), nullable=True),
        sa.Column("strength", sa.Numeric(precision=24, scale=6), nullable=True),
        sa.Column("z_t_num", sa.Integer(), nullable=True),
        sa.Column("main_change", sa.Numeric(precision=24, scale=4), nullable=True),
        sa.Column("lead_stock", sa.String(length=64), nullable=True),
        sa.Column("lead_stock_code", sa.String(length=16), nullable=True),
        sa.Column("lead_stock_pct_change", sa.Numeric(precision=14, scale=6), nullable=True),
        sa.Column("synced_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint(
            "source", "theme_code", "trade_date", name=op.f("pk_market_theme_daily")
        ),
    )
    op.create_index(
        "idx_theme_daily_trade_rank",
        "market_theme_daily",
        ["trade_date", "source", "rank"],
        unique=False,
    )
    op.create_table(
        "stock",
        sa.Column("ts_code", sa.String(length=16), nullable=False),
        sa.Column("symbol", sa.String(length=8), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("area", sa.String(length=32), nullable=True),
        sa.Column("industry", sa.String(length=64), nullable=True),
        sa.Column("fullname", sa.String(length=160), nullable=True),
        sa.Column("enname", sa.String(length=256), nullable=True),
        sa.Column("cnspell", sa.String(length=32), nullable=True),
        sa.Column("market", sa.String(length=16), nullable=True),
        sa.Column("exchange", sa.String(length=8), nullable=False),
        sa.Column("curr_type", sa.String(length=8), nullable=True),
        sa.Column("list_status", sa.String(length=1), nullable=False),
        sa.Column("list_date", sa.Date(), nullable=True),
        sa.Column("delist_date", sa.Date(), nullable=True),
        sa.Column("is_hs", sa.String(length=1), nullable=True),
        sa.Column("act_name", sa.String(length=160), nullable=True),
        sa.Column("act_ent_type", sa.String(length=64), nullable=True),
        sa.Column("synced_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "is_hs IS NULL OR is_hs IN ('N', 'H', 'S')", name=op.f("ck_stock_is_hs")
        ),
        sa.CheckConstraint(
            "list_status IN ('L', 'D', 'P', 'G')", name=op.f("ck_stock_list_status")
        ),
        sa.PrimaryKeyConstraint("ts_code", name=op.f("pk_stock")),
    )
    op.create_index("uq_stock_exchange_symbol", "stock", ["exchange", "symbol"], unique=True)
    op.create_table(
        "ths_board_moneyflow_daily",
        sa.Column("board_type", sa.String(length=16), nullable=False),
        sa.Column("board_name", sa.String(length=128), nullable=False),
        sa.Column("trade_date", sa.Date(), nullable=False),
        sa.Column("ts_code", sa.String(length=20), nullable=True),
        sa.Column("lead_stock", sa.String(length=64), nullable=True),
        sa.Column("lead_stock_price", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("pct_change", sa.Numeric(precision=14, scale=6), nullable=True),
        sa.Column("board_index", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("company_num", sa.Integer(), nullable=True),
        sa.Column("lead_stock_pct_change", sa.Numeric(precision=14, scale=6), nullable=True),
        sa.Column("net_buy_amount", sa.Numeric(precision=24, scale=4), nullable=True),
        sa.Column("net_sell_amount", sa.Numeric(precision=24, scale=4), nullable=True),
        sa.Column("net_amount", sa.Numeric(precision=24, scale=4), nullable=True),
        sa.Column("synced_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "board_type IN ('CONCEPT', 'INDUSTRY')",
            name=op.f("ck_ths_board_moneyflow_daily_board_type"),
        ),
        sa.PrimaryKeyConstraint(
            "board_type", "board_name", "trade_date", name=op.f("pk_ths_board_moneyflow_daily")
        ),
    )
    op.create_index(
        "idx_ths_board_flow_code",
        "ths_board_moneyflow_daily",
        ["ts_code", "trade_date"],
        unique=False,
    )
    op.create_index(
        "idx_ths_board_flow_day_amount",
        "ths_board_moneyflow_daily",
        ["trade_date", "board_type", sa.literal_column("net_amount DESC")],
        unique=False,
    )
    op.create_table(
        "trade_calendar",
        sa.Column("exchange", sa.String(length=8), nullable=False),
        sa.Column("cal_date", sa.Date(), nullable=False),
        sa.Column("is_open", sa.Boolean(), nullable=False),
        sa.Column("pretrade_date", sa.Date(), nullable=True),
        sa.Column("synced_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("exchange", "cal_date", name=op.f("pk_trade_calendar")),
    )
    op.create_table(
        "concept_board_daily",
        sa.Column("source", sa.String(length=8), server_default="THS", nullable=False),
        sa.Column("ts_code", sa.String(length=20), nullable=False),
        sa.Column("trade_date", sa.Date(), nullable=False),
        sa.Column("close", sa.Numeric(precision=20, scale=6), nullable=False),
        sa.Column("open", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("high", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("low", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("pre_close", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("avg_price", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("change", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("pct_change", sa.Numeric(precision=14, scale=6), nullable=True),
        sa.Column("volume", sa.Numeric(precision=24, scale=4), nullable=True),
        sa.Column("turnover_rate", sa.Numeric(precision=14, scale=6), nullable=True),
        sa.Column("total_mv", sa.Numeric(precision=24, scale=4), nullable=True),
        sa.Column("float_mv", sa.Numeric(precision=24, scale=4), nullable=True),
        sa.Column("synced_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["source", "ts_code"],
            ["concept_board.source", "concept_board.ts_code"],
            name="fk_concept_daily_board",
        ),
        sa.PrimaryKeyConstraint(
            "source", "ts_code", "trade_date", name=op.f("pk_concept_board_daily")
        ),
    )
    op.create_index(
        "idx_concept_daily_trade_board",
        "concept_board_daily",
        ["trade_date", "source", "ts_code"],
        unique=False,
    )
    op.create_table(
        "concept_board_member",
        sa.Column("source", sa.String(length=8), server_default="THS", nullable=False),
        sa.Column("ts_code", sa.String(length=20), nullable=False),
        sa.Column("con_code", sa.String(length=16), nullable=False),
        sa.Column("con_name", sa.String(length=64), nullable=True),
        sa.Column("weight", sa.Numeric(precision=14, scale=8), nullable=True),
        sa.Column("in_date", sa.Date(), nullable=True),
        sa.Column("out_date", sa.Date(), nullable=True),
        sa.Column("is_current", sa.Boolean(), nullable=False),
        sa.Column("observed_at", sa.Date(), nullable=False),
        sa.Column("synced_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["con_code"], ["stock.ts_code"], name=op.f("fk_concept_board_member_con_code_stock")
        ),
        sa.ForeignKeyConstraint(
            ["source", "ts_code"],
            ["concept_board.source", "concept_board.ts_code"],
            name="fk_concept_member_board",
        ),
        sa.PrimaryKeyConstraint(
            "source", "ts_code", "con_code", name=op.f("pk_concept_board_member")
        ),
    )
    op.create_index(
        "idx_concept_member_stock",
        "concept_board_member",
        ["con_code", "source", "ts_code"],
        unique=False,
    )
    op.create_table(
        "etf_daily",
        sa.Column("ts_code", sa.String(length=16), nullable=False),
        sa.Column("trade_date", sa.Date(), nullable=False),
        sa.Column("open", sa.Numeric(precision=20, scale=6), nullable=False),
        sa.Column("high", sa.Numeric(precision=20, scale=6), nullable=False),
        sa.Column("low", sa.Numeric(precision=20, scale=6), nullable=False),
        sa.Column("close", sa.Numeric(precision=20, scale=6), nullable=False),
        sa.Column("pre_close", sa.Numeric(precision=20, scale=6), nullable=False),
        sa.Column("change", sa.Numeric(precision=20, scale=6), nullable=False),
        sa.Column("pct_chg", sa.Numeric(precision=14, scale=6), nullable=False),
        sa.Column("volume", sa.Numeric(precision=24, scale=4), nullable=False),
        sa.Column("amount", sa.Numeric(precision=24, scale=4), nullable=False),
        sa.Column("adj_factor", sa.Numeric(precision=24, scale=8), nullable=True),
        sa.Column("synced_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["ts_code"], ["etf.ts_code"], name=op.f("fk_etf_daily_ts_code_etf")
        ),
        sa.PrimaryKeyConstraint("ts_code", "trade_date", name=op.f("pk_etf_daily")),
        postgresql_partition_by="RANGE (trade_date)",
    )
    op.create_index(
        "idx_etf_daily_trade_code", "etf_daily", ["trade_date", "ts_code"], unique=False
    )
    op.create_table(
        "etf_share_size_daily",
        sa.Column("ts_code", sa.String(length=16), nullable=False),
        sa.Column("trade_date", sa.Date(), nullable=False),
        sa.Column("etf_name", sa.String(length=96), nullable=True),
        sa.Column("total_share", sa.Numeric(precision=24, scale=4), nullable=False),
        sa.Column("total_size", sa.Numeric(precision=24, scale=4), nullable=False),
        sa.Column("nav", sa.Numeric(precision=20, scale=8), nullable=True),
        sa.Column("close", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("exchange", sa.String(length=8), nullable=False),
        sa.Column("synced_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["ts_code"], ["etf.ts_code"], name=op.f("fk_etf_share_size_daily_ts_code_etf")
        ),
        sa.PrimaryKeyConstraint("ts_code", "trade_date", name=op.f("pk_etf_share_size_daily")),
        postgresql_partition_by="RANGE (trade_date)",
    )
    op.create_index(
        "idx_etf_share_trade_code", "etf_share_size_daily", ["trade_date", "ts_code"], unique=False
    )
    op.create_table(
        "index_daily_basic",
        sa.Column("ts_code", sa.String(length=20), nullable=False),
        sa.Column("trade_date", sa.Date(), nullable=False),
        sa.Column("total_mv", sa.Numeric(precision=24, scale=4), nullable=True),
        sa.Column("float_mv", sa.Numeric(precision=24, scale=4), nullable=True),
        sa.Column("total_share", sa.Numeric(precision=24, scale=4), nullable=True),
        sa.Column("float_share", sa.Numeric(precision=24, scale=4), nullable=True),
        sa.Column("free_share", sa.Numeric(precision=24, scale=4), nullable=True),
        sa.Column("turnover_rate", sa.Numeric(precision=14, scale=6), nullable=True),
        sa.Column("turnover_rate_f", sa.Numeric(precision=14, scale=6), nullable=True),
        sa.Column("pe", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("pe_ttm", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("pb", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("synced_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["ts_code"],
            ["market_index.ts_code"],
            name=op.f("fk_index_daily_basic_ts_code_market_index"),
        ),
        sa.PrimaryKeyConstraint("ts_code", "trade_date", name=op.f("pk_index_daily_basic")),
    )
    op.create_table(
        "market_index_daily",
        sa.Column("ts_code", sa.String(length=20), nullable=False),
        sa.Column("trade_date", sa.Date(), nullable=False),
        sa.Column("close", sa.Numeric(precision=20, scale=6), nullable=False),
        sa.Column("open", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("high", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("low", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("pre_close", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("change", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("pct_chg", sa.Numeric(precision=14, scale=6), nullable=True),
        sa.Column("volume", sa.Numeric(precision=24, scale=4), nullable=True),
        sa.Column("amount", sa.Numeric(precision=24, scale=4), nullable=True),
        sa.Column("synced_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["ts_code"],
            ["market_index.ts_code"],
            name=op.f("fk_market_index_daily_ts_code_market_index"),
        ),
        sa.PrimaryKeyConstraint("ts_code", "trade_date", name=op.f("pk_market_index_daily")),
    )
    op.create_index(
        "idx_market_index_daily_trade_code",
        "market_index_daily",
        ["trade_date", "ts_code"],
        unique=False,
    )
    op.create_table(
        "market_index_weight",
        sa.Column("index_code", sa.String(length=20), nullable=False),
        sa.Column("snapshot_date", sa.Date(), nullable=False),
        sa.Column("con_code", sa.String(length=16), nullable=False),
        sa.Column("weight", sa.Numeric(precision=14, scale=8), nullable=False),
        sa.Column("synced_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["con_code"], ["stock.ts_code"], name=op.f("fk_market_index_weight_con_code_stock")
        ),
        sa.ForeignKeyConstraint(
            ["index_code"],
            ["market_index.ts_code"],
            name=op.f("fk_market_index_weight_index_code_market_index"),
        ),
        sa.PrimaryKeyConstraint(
            "index_code", "snapshot_date", "con_code", name=op.f("pk_market_index_weight")
        ),
    )
    op.create_index(
        "idx_index_weight_member",
        "market_index_weight",
        ["con_code", "snapshot_date", "index_code"],
        unique=False,
    )
    op.create_table(
        "market_theme_member_daily",
        sa.Column("source", sa.String(length=8), server_default="DC", nullable=False),
        sa.Column("trade_date", sa.Date(), nullable=False),
        sa.Column("theme_code", sa.String(length=20), nullable=False),
        sa.Column("ts_code", sa.String(length=16), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=True),
        sa.Column("industry_code", sa.String(length=20), nullable=True),
        sa.Column("industry", sa.String(length=64), nullable=True),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("hot_num", sa.Integer(), nullable=True),
        sa.Column("synced_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["ts_code"], ["stock.ts_code"], name=op.f("fk_market_theme_member_daily_ts_code_stock")
        ),
        sa.PrimaryKeyConstraint(
            "source",
            "trade_date",
            "theme_code",
            "ts_code",
            name=op.f("pk_market_theme_member_daily"),
        ),
        postgresql_partition_by="RANGE (trade_date)",
    )
    op.create_index(
        "idx_theme_member_stock",
        "market_theme_member_daily",
        ["trade_date", "ts_code", "theme_code"],
        unique=False,
    )
    op.create_table(
        "stock_company",
        sa.Column("ts_code", sa.String(length=16), nullable=False),
        sa.Column("com_name", sa.String(length=160), nullable=True),
        sa.Column("com_id", sa.String(length=32), nullable=True),
        sa.Column("exchange", sa.String(length=8), nullable=True),
        sa.Column("chairman", sa.String(length=64), nullable=True),
        sa.Column("manager", sa.String(length=64), nullable=True),
        sa.Column("secretary", sa.String(length=64), nullable=True),
        sa.Column("reg_capital", sa.Numeric(precision=24, scale=4), nullable=True),
        sa.Column("setup_date", sa.Date(), nullable=True),
        sa.Column("province", sa.String(length=32), nullable=True),
        sa.Column("city", sa.String(length=32), nullable=True),
        sa.Column("introduction", sa.Text(), nullable=True),
        sa.Column("website", sa.String(length=256), nullable=True),
        sa.Column("email", sa.String(length=128), nullable=True),
        sa.Column("office", sa.Text(), nullable=True),
        sa.Column("employees", sa.Integer(), nullable=True),
        sa.Column("main_business", sa.Text(), nullable=True),
        sa.Column("business_scope", sa.Text(), nullable=True),
        sa.Column("synced_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["ts_code"], ["stock.ts_code"], name=op.f("fk_stock_company_ts_code_stock")
        ),
        sa.PrimaryKeyConstraint("ts_code", name=op.f("pk_stock_company")),
    )
    op.create_table(
        "stock_daily",
        sa.Column("ts_code", sa.String(length=16), nullable=False),
        sa.Column("trade_date", sa.Date(), nullable=False),
        sa.Column("open", sa.Numeric(precision=20, scale=6), nullable=False),
        sa.Column("high", sa.Numeric(precision=20, scale=6), nullable=False),
        sa.Column("low", sa.Numeric(precision=20, scale=6), nullable=False),
        sa.Column("close", sa.Numeric(precision=20, scale=6), nullable=False),
        sa.Column("pre_close", sa.Numeric(precision=20, scale=6), nullable=False),
        sa.Column("change", sa.Numeric(precision=20, scale=6), nullable=False),
        sa.Column("pct_chg", sa.Numeric(precision=14, scale=6), nullable=False),
        sa.Column("volume", sa.Numeric(precision=24, scale=4), nullable=False),
        sa.Column("amount", sa.Numeric(precision=24, scale=4), nullable=False),
        sa.Column("after_hours_volume", sa.Numeric(precision=24, scale=4), nullable=True),
        sa.Column("after_hours_amount", sa.Numeric(precision=24, scale=4), nullable=True),
        sa.Column("adj_factor", sa.Numeric(precision=24, scale=8), nullable=False),
        sa.Column("turnover_rate", sa.Numeric(precision=14, scale=6), nullable=True),
        sa.Column("turnover_rate_f", sa.Numeric(precision=14, scale=6), nullable=True),
        sa.Column("volume_ratio", sa.Numeric(precision=14, scale=6), nullable=True),
        sa.Column("pe", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("pe_ttm", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("pb", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("ps", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("ps_ttm", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("dv_ratio", sa.Numeric(precision=14, scale=6), nullable=True),
        sa.Column("dv_ttm", sa.Numeric(precision=14, scale=6), nullable=True),
        sa.Column("total_share", sa.Numeric(precision=24, scale=4), nullable=True),
        sa.Column("float_share", sa.Numeric(precision=24, scale=4), nullable=True),
        sa.Column("free_share", sa.Numeric(precision=24, scale=4), nullable=True),
        sa.Column("total_mv", sa.Numeric(precision=24, scale=4), nullable=True),
        sa.Column("circ_mv", sa.Numeric(precision=24, scale=4), nullable=True),
        sa.Column("limit_status", sa.Integer(), nullable=True),
        sa.Column("up_limit", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("down_limit", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("synced_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "limit_status IS NULL OR limit_status BETWEEN 0 AND 6",
            name=op.f("ck_stock_daily_limit_status"),
        ),
        sa.ForeignKeyConstraint(
            ["ts_code"], ["stock.ts_code"], name=op.f("fk_stock_daily_ts_code_stock")
        ),
        sa.PrimaryKeyConstraint("ts_code", "trade_date", name=op.f("pk_stock_daily")),
        postgresql_partition_by="RANGE (trade_date)",
    )
    op.create_index(
        "idx_stock_daily_trade_code", "stock_daily", ["trade_date", "ts_code"], unique=False
    )
    op.create_table(
        "stock_hot_rank_daily",
        sa.Column("source", sa.String(length=8), nullable=False),
        sa.Column("trade_date", sa.Date(), nullable=False),
        sa.Column("market_type", sa.String(length=32), nullable=False),
        sa.Column("rank_type", sa.String(length=32), nullable=False),
        sa.Column("data_type", sa.String(length=32), nullable=True),
        sa.Column("ts_code", sa.String(length=16), nullable=False),
        sa.Column("ts_name", sa.String(length=64), nullable=True),
        sa.Column("rank", sa.Integer(), nullable=False),
        sa.Column("pct_change", sa.Numeric(precision=14, scale=6), nullable=True),
        sa.Column("current_price", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("concept", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("rank_reason", sa.Text(), nullable=True),
        sa.Column("hot", sa.Numeric(precision=24, scale=6), nullable=True),
        sa.Column("rank_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("synced_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("source IN ('THS', 'DC')", name=op.f("ck_stock_hot_rank_daily_source")),
        sa.CheckConstraint("rank > 0", name=op.f("ck_stock_hot_rank_daily_positive_rank")),
        sa.ForeignKeyConstraint(
            ["ts_code"], ["stock.ts_code"], name=op.f("fk_stock_hot_rank_daily_ts_code_stock")
        ),
        sa.PrimaryKeyConstraint(
            "source",
            "trade_date",
            "market_type",
            "rank_type",
            "ts_code",
            name=op.f("pk_stock_hot_rank_daily"),
        ),
        sa.UniqueConstraint(
            "source", "trade_date", "market_type", "rank_type", "rank", name="uq_hot_rank_position"
        ),
    )
    op.create_index(
        "idx_hot_rank_concept_gin",
        "stock_hot_rank_daily",
        ["concept"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index(
        "idx_hot_rank_stock_history",
        "stock_hot_rank_daily",
        ["ts_code", "trade_date", "source", "rank_type"],
        unique=False,
    )
    op.create_table(
        "stock_limit_event_daily",
        sa.Column("trade_date", sa.Date(), nullable=False),
        sa.Column("ts_code", sa.String(length=16), nullable=False),
        sa.Column("limit_type", sa.String(length=1), nullable=False),
        sa.Column("industry", sa.String(length=64), nullable=True),
        sa.Column("name", sa.String(length=64), nullable=True),
        sa.Column("close", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("pct_chg", sa.Numeric(precision=14, scale=6), nullable=True),
        sa.Column("amount_raw", sa.Numeric(precision=24, scale=4), nullable=True),
        sa.Column("limit_amount_raw", sa.Numeric(precision=24, scale=4), nullable=True),
        sa.Column("float_mv_raw", sa.Numeric(precision=24, scale=4), nullable=True),
        sa.Column("total_mv_raw", sa.Numeric(precision=24, scale=4), nullable=True),
        sa.Column("turnover_ratio", sa.Numeric(precision=14, scale=6), nullable=True),
        sa.Column("fd_amount_raw", sa.Numeric(precision=24, scale=4), nullable=True),
        sa.Column("first_time", sa.Time(), nullable=True),
        sa.Column("last_time", sa.Time(), nullable=True),
        sa.Column("open_times", sa.Integer(), nullable=True),
        sa.Column("up_stat", sa.String(length=32), nullable=True),
        sa.Column("limit_times", sa.Integer(), nullable=True),
        sa.Column("synced_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "limit_type IN ('U', 'D', 'Z')", name=op.f("ck_stock_limit_event_daily_limit_type")
        ),
        sa.ForeignKeyConstraint(
            ["ts_code"], ["stock.ts_code"], name=op.f("fk_stock_limit_event_daily_ts_code_stock")
        ),
        sa.PrimaryKeyConstraint(
            "trade_date", "ts_code", "limit_type", name=op.f("pk_stock_limit_event_daily")
        ),
    )
    op.create_index(
        "idx_limit_event_day_type",
        "stock_limit_event_daily",
        ["trade_date", "limit_type", "ts_code"],
        unique=False,
    )
    op.create_index(
        "idx_limit_event_stock_history",
        "stock_limit_event_daily",
        ["ts_code", "trade_date", "limit_type"],
        unique=False,
    )
    op.create_table(
        "stock_limit_step_daily",
        sa.Column("trade_date", sa.Date(), nullable=False),
        sa.Column("ts_code", sa.String(length=16), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=True),
        sa.Column("nums", sa.Integer(), nullable=False),
        sa.Column("synced_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("nums > 0", name=op.f("ck_stock_limit_step_daily_positive_nums")),
        sa.ForeignKeyConstraint(
            ["ts_code"], ["stock.ts_code"], name=op.f("fk_stock_limit_step_daily_ts_code_stock")
        ),
        sa.PrimaryKeyConstraint("trade_date", "ts_code", name=op.f("pk_stock_limit_step_daily")),
    )
    op.create_index(
        "idx_limit_step_day_nums",
        "stock_limit_step_daily",
        ["trade_date", sa.literal_column("nums DESC"), "ts_code"],
        unique=False,
    )
    op.create_table(
        "stock_moneyflow_daily",
        sa.Column("ts_code", sa.String(length=16), nullable=False),
        sa.Column("trade_date", sa.Date(), nullable=False),
        sa.Column("buy_sm_vol", sa.Numeric(precision=24, scale=4), nullable=True),
        sa.Column("sell_sm_vol", sa.Numeric(precision=24, scale=4), nullable=True),
        sa.Column("buy_md_vol", sa.Numeric(precision=24, scale=4), nullable=True),
        sa.Column("sell_md_vol", sa.Numeric(precision=24, scale=4), nullable=True),
        sa.Column("buy_lg_vol", sa.Numeric(precision=24, scale=4), nullable=True),
        sa.Column("sell_lg_vol", sa.Numeric(precision=24, scale=4), nullable=True),
        sa.Column("buy_elg_vol", sa.Numeric(precision=24, scale=4), nullable=True),
        sa.Column("sell_elg_vol", sa.Numeric(precision=24, scale=4), nullable=True),
        sa.Column("net_mf_vol", sa.Numeric(precision=24, scale=4), nullable=True),
        sa.Column("buy_sm_amount", sa.Numeric(precision=24, scale=4), nullable=True),
        sa.Column("sell_sm_amount", sa.Numeric(precision=24, scale=4), nullable=True),
        sa.Column("buy_md_amount", sa.Numeric(precision=24, scale=4), nullable=True),
        sa.Column("sell_md_amount", sa.Numeric(precision=24, scale=4), nullable=True),
        sa.Column("buy_lg_amount", sa.Numeric(precision=24, scale=4), nullable=True),
        sa.Column("sell_lg_amount", sa.Numeric(precision=24, scale=4), nullable=True),
        sa.Column("buy_elg_amount", sa.Numeric(precision=24, scale=4), nullable=True),
        sa.Column("sell_elg_amount", sa.Numeric(precision=24, scale=4), nullable=True),
        sa.Column("net_mf_amount", sa.Numeric(precision=24, scale=4), nullable=True),
        sa.Column("synced_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["ts_code"], ["stock.ts_code"], name=op.f("fk_stock_moneyflow_daily_ts_code_stock")
        ),
        sa.PrimaryKeyConstraint("ts_code", "trade_date", name=op.f("pk_stock_moneyflow_daily")),
        postgresql_partition_by="RANGE (trade_date)",
    )
    op.create_index(
        "idx_stock_moneyflow_trade_code",
        "stock_moneyflow_daily",
        ["trade_date", "ts_code"],
        unique=False,
    )
    op.create_table(
        "stock_suspend_daily",
        sa.Column("ts_code", sa.String(length=16), nullable=False),
        sa.Column("trade_date", sa.Date(), nullable=False),
        sa.Column("suspend_type", sa.String(length=1), nullable=False),
        sa.Column("suspend_timing", sa.String(length=64), nullable=True),
        sa.Column("synced_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "suspend_type IN ('S', 'R')", name=op.f("ck_stock_suspend_daily_suspend_type")
        ),
        sa.ForeignKeyConstraint(
            ["ts_code"], ["stock.ts_code"], name=op.f("fk_stock_suspend_daily_ts_code_stock")
        ),
        sa.PrimaryKeyConstraint(
            "ts_code", "trade_date", "suspend_type", name=op.f("pk_stock_suspend_daily")
        ),
    )
    op.create_index(
        "idx_suspend_day_type",
        "stock_suspend_daily",
        ["trade_date", "suspend_type", "ts_code"],
        unique=False,
    )
    op.create_table(
        "stock_technical_daily",
        sa.Column("ts_code", sa.String(length=16), nullable=False),
        sa.Column("trade_date", sa.Date(), nullable=False),
        sa.Column("open_hfq", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("open_qfq", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("close_hfq", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("close_qfq", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("high_hfq", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("high_qfq", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("low_hfq", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("low_qfq", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("pre_close_hfq", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("pre_close_qfq", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("macd_dif", sa.Numeric(precision=20, scale=8), nullable=True),
        sa.Column("macd_dea", sa.Numeric(precision=20, scale=8), nullable=True),
        sa.Column("macd", sa.Numeric(precision=20, scale=8), nullable=True),
        sa.Column("kdj_k", sa.Numeric(precision=20, scale=8), nullable=True),
        sa.Column("kdj_d", sa.Numeric(precision=20, scale=8), nullable=True),
        sa.Column("kdj_j", sa.Numeric(precision=20, scale=8), nullable=True),
        sa.Column("rsi_6", sa.Numeric(precision=20, scale=8), nullable=True),
        sa.Column("rsi_12", sa.Numeric(precision=20, scale=8), nullable=True),
        sa.Column("rsi_24", sa.Numeric(precision=20, scale=8), nullable=True),
        sa.Column("boll_upper", sa.Numeric(precision=20, scale=8), nullable=True),
        sa.Column("boll_mid", sa.Numeric(precision=20, scale=8), nullable=True),
        sa.Column("boll_lower", sa.Numeric(precision=20, scale=8), nullable=True),
        sa.Column("cci", sa.Numeric(precision=20, scale=8), nullable=True),
        sa.Column("synced_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["ts_code"], ["stock.ts_code"], name=op.f("fk_stock_technical_daily_ts_code_stock")
        ),
        sa.PrimaryKeyConstraint("ts_code", "trade_date", name=op.f("pk_stock_technical_daily")),
        postgresql_partition_by="RANGE (trade_date)",
    )
    op.create_index(
        "idx_stock_technical_trade_code",
        "stock_technical_daily",
        ["trade_date", "ts_code"],
        unique=False,
    )
    op.create_table(
        "stock_top_inst_daily",
        sa.Column("detail_id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("trade_date", sa.Date(), nullable=False),
        sa.Column("ts_code", sa.String(length=16), nullable=False),
        sa.Column("exalter", sa.Text(), nullable=False),
        sa.Column("side", sa.SmallInteger(), nullable=False),
        sa.Column("buy", sa.Numeric(precision=24, scale=4), nullable=True),
        sa.Column("buy_rate", sa.Numeric(precision=14, scale=6), nullable=True),
        sa.Column("sell", sa.Numeric(precision=24, scale=4), nullable=True),
        sa.Column("sell_rate", sa.Numeric(precision=14, scale=6), nullable=True),
        sa.Column("net_buy", sa.Numeric(precision=24, scale=4), nullable=True),
        sa.Column("reason", sa.String(length=512), nullable=False),
        sa.Column("synced_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("side IN (0, 1)", name=op.f("ck_stock_top_inst_daily_side")),
        sa.ForeignKeyConstraint(
            ["ts_code"], ["stock.ts_code"], name=op.f("fk_stock_top_inst_daily_ts_code_stock")
        ),
        sa.PrimaryKeyConstraint("detail_id", name=op.f("pk_stock_top_inst_daily")),
    )
    op.create_index(
        "idx_top_inst_exalter_history",
        "stock_top_inst_daily",
        ["exalter", "trade_date"],
        unique=False,
    )
    op.create_index(
        "idx_top_inst_stock_history",
        "stock_top_inst_daily",
        ["ts_code", "trade_date"],
        unique=False,
    )
    op.create_index(
        "idx_top_inst_trade_stock", "stock_top_inst_daily", ["trade_date", "ts_code"], unique=False
    )
    op.create_table(
        "stock_top_list_daily",
        sa.Column("top_list_id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("trade_date", sa.Date(), nullable=False),
        sa.Column("ts_code", sa.String(length=16), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=True),
        sa.Column("close", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("pct_change", sa.Numeric(precision=14, scale=6), nullable=True),
        sa.Column("turnover_rate", sa.Numeric(precision=14, scale=6), nullable=True),
        sa.Column("amount", sa.Numeric(precision=24, scale=4), nullable=True),
        sa.Column("l_sell", sa.Numeric(precision=24, scale=4), nullable=True),
        sa.Column("l_buy", sa.Numeric(precision=24, scale=4), nullable=True),
        sa.Column("l_amount", sa.Numeric(precision=24, scale=4), nullable=True),
        sa.Column("net_amount", sa.Numeric(precision=24, scale=4), nullable=True),
        sa.Column("net_rate", sa.Numeric(precision=14, scale=6), nullable=True),
        sa.Column("amount_rate", sa.Numeric(precision=14, scale=6), nullable=True),
        sa.Column("float_values", sa.Numeric(precision=24, scale=4), nullable=True),
        sa.Column("reason", sa.String(length=512), nullable=False),
        sa.Column("synced_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["ts_code"], ["stock.ts_code"], name=op.f("fk_stock_top_list_daily_ts_code_stock")
        ),
        sa.PrimaryKeyConstraint("top_list_id", name=op.f("pk_stock_top_list_daily")),
        sa.UniqueConstraint("trade_date", "ts_code", "reason", name="uq_top_list_day_stock_reason"),
    )
    op.create_index(
        "idx_top_list_stock_history",
        "stock_top_list_daily",
        ["ts_code", "trade_date"],
        unique=False,
    )
    _create_initial_partitions()
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_top_list_stock_history", table_name="stock_top_list_daily")
    op.drop_table("stock_top_list_daily")
    op.drop_index("idx_top_inst_trade_stock", table_name="stock_top_inst_daily")
    op.drop_index("idx_top_inst_stock_history", table_name="stock_top_inst_daily")
    op.drop_index("idx_top_inst_exalter_history", table_name="stock_top_inst_daily")
    op.drop_table("stock_top_inst_daily")
    op.drop_index("idx_stock_technical_trade_code", table_name="stock_technical_daily")
    op.drop_table("stock_technical_daily")
    op.drop_index("idx_suspend_day_type", table_name="stock_suspend_daily")
    op.drop_table("stock_suspend_daily")
    op.drop_index("idx_stock_moneyflow_trade_code", table_name="stock_moneyflow_daily")
    op.drop_table("stock_moneyflow_daily")
    op.drop_index("idx_limit_step_day_nums", table_name="stock_limit_step_daily")
    op.drop_table("stock_limit_step_daily")
    op.drop_index("idx_limit_event_stock_history", table_name="stock_limit_event_daily")
    op.drop_index("idx_limit_event_day_type", table_name="stock_limit_event_daily")
    op.drop_table("stock_limit_event_daily")
    op.drop_index("idx_hot_rank_stock_history", table_name="stock_hot_rank_daily")
    op.drop_index(
        "idx_hot_rank_concept_gin", table_name="stock_hot_rank_daily", postgresql_using="gin"
    )
    op.drop_table("stock_hot_rank_daily")
    op.drop_index("idx_stock_daily_trade_code", table_name="stock_daily")
    op.drop_table("stock_daily")
    op.drop_table("stock_company")
    op.drop_index("idx_theme_member_stock", table_name="market_theme_member_daily")
    op.drop_table("market_theme_member_daily")
    op.drop_index("idx_index_weight_member", table_name="market_index_weight")
    op.drop_table("market_index_weight")
    op.drop_index("idx_market_index_daily_trade_code", table_name="market_index_daily")
    op.drop_table("market_index_daily")
    op.drop_table("index_daily_basic")
    op.drop_index("idx_etf_share_trade_code", table_name="etf_share_size_daily")
    op.drop_table("etf_share_size_daily")
    op.drop_index("idx_etf_daily_trade_code", table_name="etf_daily")
    op.drop_table("etf_daily")
    op.drop_index("idx_concept_member_stock", table_name="concept_board_member")
    op.drop_table("concept_board_member")
    op.drop_index("idx_concept_daily_trade_board", table_name="concept_board_daily")
    op.drop_table("concept_board_daily")
    op.drop_table("trade_calendar")
    op.drop_index("idx_ths_board_flow_day_amount", table_name="ths_board_moneyflow_daily")
    op.drop_index("idx_ths_board_flow_code", table_name="ths_board_moneyflow_daily")
    op.drop_table("ths_board_moneyflow_daily")
    op.drop_index("uq_stock_exchange_symbol", table_name="stock")
    op.drop_table("stock")
    op.drop_index("idx_theme_daily_trade_rank", table_name="market_theme_daily")
    op.drop_table("market_theme_daily")
    op.drop_table("market_index")
    op.drop_table("etf")
    op.drop_table("concept_board")
    # ### end Alembic commands ###
